// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYZ7hhoJ4PKgNwv4OYRKgsyVvaz6uPEg',
    appId: '1:50335315057:web:70b03282e78710829bd7d0',
    messagingSenderId: '50335315057',
    projectId: 'sso-6ef47',
    authDomain: 'sso-6ef47.firebaseapp.com',
    storageBucket: 'sso-6ef47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdzbBzeeoo_eJxht_v5QGE8frI3niLHQo',
    appId: '1:50335315057:android:077d4687ef92793a9bd7d0',
    messagingSenderId: '50335315057',
    projectId: 'sso-6ef47',
    storageBucket: 'sso-6ef47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJoITBhy-xtO2gvs0nGmbSlSy3rttf798',
    appId: '1:50335315057:ios:2479b79c8bfc5a9e9bd7d0',
    messagingSenderId: '50335315057',
    projectId: 'sso-6ef47',
    storageBucket: 'sso-6ef47.appspot.com',
    iosBundleId: 'com.example.ssoTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJoITBhy-xtO2gvs0nGmbSlSy3rttf798',
    appId: '1:50335315057:ios:2479b79c8bfc5a9e9bd7d0',
    messagingSenderId: '50335315057',
    projectId: 'sso-6ef47',
    storageBucket: 'sso-6ef47.appspot.com',
    iosBundleId: 'com.example.ssoTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzYZ7hhoJ4PKgNwv4OYRKgsyVvaz6uPEg',
    appId: '1:50335315057:web:314a7de5ec5965639bd7d0',
    messagingSenderId: '50335315057',
    projectId: 'sso-6ef47',
    authDomain: 'sso-6ef47.firebaseapp.com',
    storageBucket: 'sso-6ef47.appspot.com',
  );
}
